### ISSUE TITLE
Code quality issue in function calcGeomMeanLongSun?

### ISSUE THREAD

**Issue by kebekus** [buelowp/sunset#26]
Dear Buelowp,

thank you for providing this wonderful library, which  I use in my flight navigation app https://github.com/Akaflieg-Freiburg/enroute. Using you code, my compiler warned about a unused result in the function **calcGeomMeanLongSun**:

```
double SunSet::calcGeomMeanLongSun(double t)
{
    if (std::isnan(t)) {
        return nan("");
    }
    double L = 280.46646 + t * (36000.76983 + 0.0003032 * t);

    std::fmod(L, 360.0);
  
    return L;              // in degrees
}
```
Is seems that the result of the call std::fmod(L, 360.0) is never used. I presume that you wish to change the value for L, correct?

Best wishes from Germany,

Stefan Kebekus.

**Comment by buelowp** [comment]
Interesting, not sure how I missed that. I need to go back to the original, and take a look and see what happened. I'll update later when I have time to dig into it. Thank you.

**Comment by buelowp** [comment]
OK, so testing a change which assigns L = std::fmod(L, 360.0) doesn't seem to break or even change anything. I'm trying to understand why, but honestly, the math is way above my head, I just turned it into a library. For now, the result is generally always accurate, so I would be hesitant to make any changes right now. I'll keep digging into it, but it's pry going to stay as is unless there is an invalid calculation as a result.

**Comment by buelowp** [comment]
The original code took a resource intensive path to determine the remainder of the value L by either adding or subtracting 360 until you got to a value equal to L%360 for a float, and then returning what was left. I suspect it was written this way because fmod did not exist at the time, and you couldn't do a mod on floats. 
```
  while( (int) L >  360 )
    {
      L -= 360.0;

    }
  while(  L <  0)
    {
      L += 360.0;

    }
```
I migrated to fmod, but made a mistake. For some reason, it doesn't seem to cause a change in behavior, even though the L value before the fmod is > 7000 for current dates. I plan to make the change and push it to master shortly so I can test it more and see if it breaks anything. I won't release the code until I'm sure it's good.
